# Generated by Django 5.2.16 on 2026-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=300)),
                ('health_system_name', models.CharField(blank=True, max_length=300)),
                ('filename', models.CharField(max_length=300)),
                ('pdf', models.BinaryField()),
                ('form_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
